[build-system]
# Requirements for building the compiled package
requires = [
        "wheel",
        "setuptools >=40.8",
        "cython >=3",
        "numpy>=2.0"
]
build-backend = "setuptools.build_meta"
